import { FC } from "react";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

const PrivacyPage: FC = () => {
  return (
    <>
      <Navigation />
      <div className="bg-background text-foreground">
        <div className="container mx-auto px-4 py-8 pt-28 sm:pt-32">
          <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
          <p className="mb-4">Last updated: August 17, 2025</p>
          <p className="mb-4">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p className="mb-4">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

          <h2 className="text-2xl font-bold mt-6 mb-2">Interpretation and Definitions</h2>

          <h3 className="text-xl font-bold mt-4 mb-2">Interpretation</h3>
          <p className="mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

          <h3 className="text-xl font-bold mt-4 mb-2">Definitions</h3>
          <p className="mb-4">For the purposes of this Privacy Policy:</p>
          <ul className="list-disc list-inside mb-4 space-y-2">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AllergenAI.</li>
            <li><strong>Country</strong> refers to: the country</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the AllergenAI mobile application.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className="text-2xl font-bold mt-6 mb-2">Collecting and Using Your Personal Data</h2>
          <h3 className="text-xl font-bold mt-4 mb-2">Types of Data Collected</h3>

          <h4 className="text-lg font-bold mt-4 mb-2">Personal Data</h4>
          <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc list-inside mb-4">
            <li>Email address</li>
            <li>Allergy information (including custom allergens)</li>
          </ul>

          <h4 className="text-lg font-bold mt-4 mb-2">Usage Data</h4>
          <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
          <p className="mb-4">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), unique device identifiers and other diagnostic data.</p>
          <p className="mb-4">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, and Your mobile operating system.</p>

          <h3 className="text-xl font-bold mt-4 mb-2">Use of Your Personal Data</h3>
          <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc list-inside mb-4 space-y-2">
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service and to provide its core functionality of identifying potential allergens.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
            <li><strong>To contact You:</strong> To contact You by email regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
          </ul>

          <h3 className="text-xl font-bold mt-4 mb-2">Retention of Your Personal Data</h3>
          <p className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

          <h3 className="text-xl font-bold mt-4 mb-2">Transfer of Your Personal Data</h3>
          <p className="mb-4">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
          <p className="mb-4">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

          <h3 className="text-xl font-bold mt-4 mb-2">Disclosure of Your Personal Data</h3>
          <p className="mb-4">We may share Your personal information with Service Providers to monitor and analyze the use of our Service, and to provide authentication and paywall functionalities.</p>

          <h3 className="text-xl font-bold mt-4 mb-2">Security of Your Personal Data</h3>
          <p className="mb-4">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

          <h2 className="text-2xl font-bold mt-6 mb-2">Children's Privacy</h2>
          <p className="mb-4">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>

          <h2 className="text-2xl font-bold mt-6 mb-2">Links to Other Websites</h2>
          <p className="mb-4">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
          <p className="mb-4">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

          <h2 className="text-2xl font-bold mt-6 mb-2">Changes to this Privacy Policy</h2>
          <p className="mb-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
          <p className="mb-4">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

          <h2 className="text-2xl font-bold mt-6 mb-2">Contact Us</h2>
          <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc list-inside mb-4">
            <li>By email: support@allergenai.app</li>
          </ul>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PrivacyPage;
